In [42]:
import numpy as np
import pandas as pd

In [8]:
class Stack:

    def __init__(self):
        self.stack = []

    def add(self, dataval):
# Use list append method to add element
        if dataval not in self.stack:
            self.stack.append(dataval)
            return True
        else:
            return False
# Use peek to look at the top of the stack

    def peek(self):     
	    return self.stack[-1]
    
    def remove(self):
        self.stack.pop()
#         return True
        

In [11]:
a = Stack()

In [12]:
a.add('Ameya')
a.add('Cajkh')

True

In [13]:
a.remove()

In [14]:
a.peek()

'Ameya'

In [32]:
"""
Cumulative sum of a list [a, b, c, ...] is defined as [a, a+b, a+b+c, ...]. 
Write a function cumulative_sum to compute cumulative sum of a list. """

a = [1,2,3,4]

b = []

cum = a[0]

for i in a[1:]:
    cum += i
    b.append(cum)
    
print(b)

[3, 6, 10]


In [34]:
def factorial(n):
    
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
    
def cum_mult(arr):
    
    b = []
    cum = arr[0]
    
    b.append(cum)
    
    for i in arr[1:]:
        cum *= i
        b.append(cum)
        
    return b

In [36]:
print(cum_sum(a))
print(cum_mult(a))

[1, 3, 6, 10]
[1, 2, 6, 24]


In [4]:
factorial(8)

40320

In [6]:
!pip install algorithms

     |████████████████████████████████| 133kB 787kB/s eta 0:00:01


In [12]:
a= ['a','b','c','d'] 
list(enumerate(a))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [13]:
for i in enumerate(a):
    print(i)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')


In [21]:
def pythogoras(x,y,z):
    
    if x**2 + y**2 == z**2:
        return True
    return False

In [22]:
pythogoras(3,4,5)

True

In [37]:
dic = {'a':1,'b':2,'c':3}

In [38]:
'a' in dic

True

In [52]:
# a = np.array([(1,2,3,4),(4,5,6),(4,5)])

a = np.array( [ (1,7,3,4),(3,2,4,1) ] )

In [53]:
a

array([[1, 7, 3, 4],
       [3, 2, 4, 1]])

In [54]:
a.flatten()

array([1, 7, 3, 4, 3, 2, 4, 1])

In [55]:
a.ravel()

array([1, 7, 3, 4, 3, 2, 4, 1])

In [56]:
a = [[1,2,3],[4,5,6]]

In [64]:
a[0]

[1, 2, 3]

In [66]:
for i in a:
    for ele in i:
        print(ele)

1
2
3
4
5
6


In [70]:
def flatten(array):
    
    otp = []
    
    for i in array:
        for ele in i:
            otp.append(ele)
    return otp

In [71]:
flatten(array = [[1,2,3],[5,6,8,9,0]])

[1, 2, 3, 5, 6, 8, 9, 0]